### ISSUE TITLE
How would one proceed to write the Tree sturcture to a file for later read

### ISSUE THREAD

**Issue by rnadhani-ns** [zmap/go-iptree#7]
Basically, my use case is to build tree once and then write it to a file (similar to a DB) with the value of this referencing another data (integer).

Then other process/services/libaries can just read the DB in memory and get the associated data to it.

I dont want to read the IP file to contruct the tree in memory everytime as the IP list is huge.

Any suggestion?

**Comment by dadrian** [comment]
You'd have to write a custom serialization method, which is outside the scope of this project.
